sentiment-classification:
  - angry-tweets
named-entity-recognition:
  - dansk
linguistic-acceptability:
  - scala-da
reading-comprehension:
  - scandiqa-da
summarization:
  - nordjylland-news
knowledge:
  - danske-talemaader
  - danish-citizen-tests
common-sense-reasoning:
  - hellaswag-da
